<?php $this->headTitle()->prepend($this->translate('My Instagram Profile')); ?>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <h2><i class="fa fa-instagram"></i> Instagram Sync <small><?php echo $this->translate('Setup your Instagram profile')?></small></h2>
                <hr/>
                <p><?php echo $this->translate('Here you can set the Instagram profile to share your photos in this website. When you set your instagram here, the photos will be published in your website profile.')?></p>
                <blockquote><?php echo $this->translate('Click on the Instagram Login button. You will redirect at the instagram website where you have to accept the permissions.')?></blockquote>
                <p>
                    <a class="btn btn-primary" href="/instagram/auth"><i class="fa fa-instagram"></i> <?php echo $this->translate('Instagram Login')?></a>
                </p>
            </div>
        </div>
    </div>
</div>

